print("hello world")
print('Whats is your name?')
myName = input()
print("It is good meet you, " + myName)
print("The lenght of your name is: ")
print(len(myName))

print("What is our age?")
myAge = input()
print("You will be " + str(int(myAge) + 1) + "in a year. ")